### ISSUE TITLE
Show that the ensemble database can be opened and read

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/ForecastGenerator#9]
report out the number of records after reading the file.

**Comment by HenryGeorgist** [comment]
i ran into an issue where the firo_timeseries.jar was not added to the wat compute - need to make sure to add that to wat/jar

**Comment by HenryGeorgist** [comment]
now I am recieving an exception in wat:
2020-02-18 19:51:25.540 -0500 SEVERE: (ForecastGeneratorAlternative.java:181) null
java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Temp\wat\testing\FG\TS_ensemble.db
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at hec.ensemble.JdbcEnsembleTimeSeriesDatabase.<init>(JdbcEnsembleTimeSeriesDatabase.java:50)
	at forecastGenerator.ForecastGeneratorAlternative.compute(ForecastGeneratorAlternative.java:172)
	at forecastGenerator.ForecastGeneratorPlugin.compute(ForecastGeneratorPlugin.java:105)
	at hec2.wat.model.WatSimulation.computeModel(WatSimulation.java:140)
	at hec2.wat.model.WatSimulation.computeRealization(WatSimulation.java:1467)
	at hec2.wat.model.FrmSimulation.computeRealization(FrmSimulation.java:1022)
	at hec2.wat.model.FrmSimulation.computeRealizations(FrmSimulation.java:1209)
	at hec2.wat.model.WatSimulation.compute2(WatSimulation.java:1277)
	at hec2.wat.model.FrmSimOptions.compute(FrmSimOptions.java:2)
	at hec2.wat.plugin.simulationcompute.SingleThreadedSequentialEngine.computeRealizations(SingleThreadedSequentialEngine.java:62)
	at hec2.wat.model.WatSimulation.compute(WatSimulation.java:815)
	at hec2.wat.editors.WatComputeProgressDialog$WatComputeProgressPanel$2.run(WatComputeProgressDialog.java:16)
	at java.lang.Thread.run(Unknown Source)

**Comment by HenryGeorgist** [comment]
the dependency provided on FIRO_TSensembles project fixed my exception above, now i have a cast issue:
2020-02-19 08:27:47.195 -0500 SEVERE: (ForecastGeneratorAlternative.java:181) null
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lhec.ensemble.TimeSeriesIdentifier;
	at hec.ensemble.JdbcEnsembleTimeSeriesDatabase.getTimeSeriesIDs(JdbcEnsembleTimeSeriesDatabase.java:351)
	at forecastGenerator.ForecastGeneratorAlternative.compute(ForecastGeneratorAlternative.java:173)
	at forecastGenerator.ForecastGeneratorPlugin.compute(ForecastGeneratorPlugin.java:105)
	at hec2.wat.model.WatSimulation.computeModel(WatSimulation.java:140)
	at hec2.wat.model.WatSimulation.computeRealization(WatSimulation.java:1467)
	at hec2.wat.model.FrmSimulation.computeRealization(FrmSimulation.java:1022)
	at hec2.wat.model.FrmSimulation.computeRealizations(FrmSimulation.java:1209)
	at hec2.wat.model.WatSimulation.compute2(WatSimulation.java:1277)
	at hec2.wat.model.FrmSimOptions.compute(FrmSimOptions.java:2)
	at hec2.wat.plugin.simulationcompute.SingleThreadedSequentialEngine.computeRealizations(SingleThreadedSequentialEngine.java:62)
	at hec2.wat.model.WatSimulation.compute(WatSimulation.java:815)
	at hec2.wat.editors.WatComputeProgressDialog$WatComputeProgressPanel$2.run(WatComputeProgressDialog.java:16)
	at java.lang.Thread.run(Unknown Source)

**Comment by HenryGeorgist** [comment]
Reading now works.
